spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 3.113.71.211:9300
      repositories:
        enabled: true
  redis:
    host: 3.113.71.211
    port: 6379
    password: ce30
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 200000
## kafka
logic:
  kafka:
    broker:
      host: 3.113.71.211
      port: 9092
    topic:
      topic-torrent-meta-info : torrent-meta-info
    consumer:
      group-id: exchange-group
