spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 3.113.71.211:9300
      repositories:
        enabled: true
## kafka
logic:
  kafka:
    broker:
      host: 3.113.71.211
      port: 9092
    topic:
      topic-torrent-meta-info : torrent-meta-info
    consumer:
      group-id: exchange-group
