## netty服务器端口
logic:
  udp:
    port: 6998
  connect-timeout-sec: 30
  ##kafka配置
  kafka:
    broker:
      host: 3.113.71.211
      port: 9092
    topic:
      topic-info-hash-output: info-hash-output
      topic-torrent-meta-info: torrent-meta-info
    consumer:
      group-id: exchange-group
spring:
  redis:
    host: 3.113.71.211
    port: 6379
    password: ce30
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 200000
logging:
  com.lzh: info
