## netty服务器端口
logic:
  udp:
    port: 6998
  connect-timeout-sec: 10
  ##kafka配置
  kafka:
    broker:
      host: 3.113.71.211
      port: 9092
    topic:
      topic-info-hash-output: info-hash-output
      topic-torrent-meta-info : torrent-meta-info
    consumer:
      group-id: exchange-group
logging:
  com.lzh: info
