## netty服务器端口
logic:
  udp:
    port: 6688
  so:
    backlog: 100
    rcvbuf: 268435456
    sndbuf: 65536

spring:
  redis:
    host: 18.179.203.137
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9300
#      repositories:
#        enabled: true
#      properties:
#        path:
#          logs: ./elasticsearch/log #elasticsearch日志存储目录
#          data: ./elasticsearch/data #elasticsearch数据存储目录
logging:
  com.lzh: info
